---
- hosts: localhost
  become: true
  tasks:
    - name: Adding users with with_items
      user: name={{item}} state=present 
      with_items:
        - apache2
        - libapache2-mod-wsgi
        - python-pip
        - python-virtualenv