---
- hosts:  localhost
  become: true
  tasks:
    - name: Installing apache
      yum:
        name: httpd
        state:  latest
    
    - name: start and enable apache2
      service:
        name: httpd
        state:  started
        enable: yes

    - name: create index.html
      file:
        path: /var/html/index.html
        state:  touch
    
    - name: Adding Hello world in index.html
      lineinfile:
        path: /var/html/index.html
        line: "Hello world"