---
- hosts: localhost
  become: true
  tasks:
    - name: install web components
      apt: name={{item}} state=present update_cache=yes
      with_items:
        - apache2
        - python-setuptools
        - python-dev build-essential
        - python-pip python-mysqldb

   
        
